### ISSUE TITLE
Mixer APP Can't connect quest2

### ISSUE THREAD

**Issue by 058Enjoyli** [fabio914/RealityMixer#78]
Just can't    already in same wifi.😢😢
![F408FE6E-44DD-4A50-B5A8-AD3CCA9CFF6A](https://user-images.githubusercontent.com/77785205/119268164-4789f480-bc24-11eb-9645-32727e14050c.jpeg)
![813908A7-81BD-4A3A-A55A-0684D5E0A28F](https://user-images.githubusercontent.com/77785205/119268166-49ec4e80-bc24-11eb-8afc-9e4ee22e40fa.png)

**Comment by happyplacetraveler** [comment]
I’ve fixed this before - 1) (almost always fixes issue) Reboot modem/gateway/router.

If that didn’t resolve the issue….
 2) Power down iPhone and then when restarting HOLD THE POWER BUTTON UNTIL YOU SEE THE APPLE LOGO (I used to be an iOS tech support agent for Apple - this resolves a lot of iPhone issues) & also reboot Quest.

From what I can tell, this can occur when a device falls out of 5ghz and down to the 2.4ghz (if you have auto switching) because it couldn’t maintain speed on the higher bands.    Also, if there is a lot of nearby wifi traffic or interference (water flowing through pipes that are between you and your router, running the microwave, streaming video on other devices, etc).     Rebooting the router/gateway allows it to correct issues and improve efficiency under changed conditions. Rebooting iPhone and oculus if the router reboot didn’t do it allows the devices to effectively connect and to connect in a similar time range so that they’re likely to keep a strong link between them once they’re both up. 

Alternative - plug in wired for a few minutes then go back to wireless/WiFi.   Once a few hrs elapses, the environmental situations as well as the electronic communication ones are likely to cycle or change; a few minutes wired allows you to continue playing / mixing reality while providing a brief break for all devices which are more likely to work properly once time passes. 

*** I do not believe this is an app issue because the same issue occurs sometimes with Bluetooth connections and it can occur when two devices on a network need to maintain handshaking with one another.   This is a wireless communications challenge rather than one specific to an app or to hardware++I think!+.   I could be wrong but I’ve tested these solutions at length and the solutions seem to match this idea.

Hope it helps, 
-Brent

**Comment by 058Enjoyli** [comment]
now i know what problem，is ROUTER problem，i changed an onther ROUTER ，IT work very perfect！thank you somuch！！！

**Comment by happyplacetraveler** [comment]
Glad to hear you got it working. What you said goes along with what I do which is to give router priority to my Quest and and my iPhone, so all other traffic takes a back seat to whatever data those two are using. Again, glad to hear the good news. I'm sure Fabio will mirror the same feelings :)
